### ISSUE TITLE
Unboxing and Initial Hardware Setup

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#1]
Unbox the Raspberry Pi and perform initial hardware setup, including power and peripherals.

#### Tasks:
- [x] Power on the Raspberry Pi and complete the setup wizard.
- [x] Configure the network settings (Wi-Fi or Ethernet).
- [x] Change default password and update system settings.

**Comment by kxs1119** [comment]
Able to set up and connected to Wi-Fi.
