### ISSUE TITLE
Initiate Expo Location and User Location Tracking

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#101]
Tasks to Implement Expo Location and User Location Tracking

- [x] Integrate Expo Location into the React Native project.

- [x] Request permissions for accessing the user’s location on app launch.

- [x] Enable continuous location updates using watchPositionAsync.

**Comment by kxs1119** [comment]
Added the capability to ask for current location and center location onto end-user
![Screenshot 2024-12-06 at 9 15 53 PM](https://github.com/user-attachments/assets/8dddd5da-c9df-40fc-a01c-c6f6473150f3)
