### ISSUE TITLE
First Boot and Configuration

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#3]
Boot the Raspberry Pi for the first time and complete the initial configuration.
#### Tasks:
- [x] Power on the Raspberry Pi and complete the setup wizard.
- [x] Configure the network settings (Wi-Fi or Ethernet).
- [x] Change default password and update system settings.
